apiVersion: syndesis.io/v1beta2
kind: Syndesis
metadata:
  name: app
spec:
  demoData: true
  addons:
    #enable due to PR job
    jaeger:
      enabled: true
    todo:
      enabled: true
  components:
    scheduled: false
    server:
      features:
        integrationStateCheckInterval: 60
        integrationLimit: 1
  devSupport: false
