apiVersion: syndesis.io/v1beta3
kind: Syndesis
metadata:
  name: app
spec:
  #
  # Uncomment & specify the OpenShift route for the Fuse Online console.
  # By default, the installation script calculates the route.
  # routeHostname: my-test-route.com
  #
  # Uncomment & specify a cron utility interval to schedule backups of application data and resources.
  # backup:
  #   schedule: every 10m
  #
  components:
    meta:
      resources: {}
    server:
      features:
        mavenRepositories: {}
      resources: {}
    database:
      resources: {}
    prometheus:
      resources: {}
  addons:
    # Enables Jaeger activity tracking.
    jaeger:
      enabled: true
    # Enables the Knative component (Technology Preview).
    knative:
      enabled: false
    # Enables Prometheus monitoring.
    ops:
      enabled: false
    # Exposes public REST API endpoints for CI/CD pipelines.
    publicApi:
      enabled: false
      # Uncomment & modify to specify the public address for invoking REST API endpoints.
      # routeHostname: public-syndesis.a.b.c.d.e
    # Enables the Todo application for confirming that sample integrations work.
    todo:
      enabled: false

